services:
  azure-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: portkey:latest
    container_name: portkey
    env_file:
      - .env
    volumes:
      - portkey-volume:/home/vscode/.azure
    working_dir: /workspaces/scripts/azure/portkey
    restart: unless-stopped
    command: sleep infinity
    tty: true

volumes:
  portkey-volume: